# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# Running the app with `streamlit run first_prototype.py` uses this config file.
# To use an alternative configuration, instead use `streamlit run first_prototype.py path-to-file/config-file-name.toml`.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# this is the text that will be shown on the first page 
[consent]

intro_and_consent = """## Welcome to our parent-chatbot.

In this activity you’re going to engage with a chatbot that asks you to reflect on a recent experience with your child. \
Please do not share any information that can be used to identify you or anyone else.

**It's important that you do not report information contain personal information about yourself or anyone else.**

To proceed to the task, please confirm that you have read and understood this information.
"""


###  This section sets up the data collection bot. ### 
# You can put in as many specific questions as you like; and 
# you can remove the 'general' question if not used
[collection]

persona = "You're a parenting coach helping parents reflect on their experiences of applying new parenting strategies."

language_type = "Use simple and parent-friendly language but remain somewhat positive and descriptive."

intro = """
Hi there -- I want to help you to think of a time you were able to use praise with your child today. \
We talk about using praise to help children know which behaviours we want to see more of, like playing calmly and being polite and kind more often. \
Sometimes, it can be really hard to notice times when you use praise or even find things to praise when interacting with your child. Those moments are often there ...even if they are really, really small!  \
Let me know when you are ready.

 \n 


"""

questions = [
    "What was happening at the time?",
    "What did you do or say to use praise with your child and how did your child react?",
    "How did that make you feel?",
    "What would you tell a younger version of yourself who is trying to use praise with their child?",
]

topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your parenting experiences." and return to the questions about their parenting experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their parenting experiences.
"""


###  This section sets up the data extraction and story generation bots. ### 

[summaries]

# Summaries.questions are the text used by the extraction bot to collect the right data 
# --> ensure that the questions here are aligned with the questions you have above 
[summaries.questions]

event = "What was happening at the time?"
actions_taken = "What did you do or say to use praise with your child and how did your child react?"
feeling = "How did that make you feel?"
recommendation = "What would you tell a younger version of yourself who is trying to connect with their child?"

[summaries.personas]

parent_1 = """
You're a 20-year-old first-time single parent whose reading age is 11 years. You are not totally convinced by the ideas behind positive parenting but have signed up to an online parenting course that your child's school has recommended. Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format.\
Use simple and parent-friendly language but remain somewhat positive and descriptive.
Use British English language and express their story in first-person language.
"""

Parent_2 = """
You're a 35-year-old parent of three whose reading age is 35 years. You have recently had a very hard time managing your and your child's emotions and child behaviour. Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format.\
Use simple and parent-friendly language and remain somewhat positive and descriptive.
Use British English language and express their story in first-person language.
"""

parenting_practitioner  = """
You're a parenting coach who works with low-SES populations. You only use simple language and short sentences. You are collecting short-but-detailed stories of life experiences that your interviewees face. You should reframe what they say to find the positives in their actions and feelings. Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and parent-friendly language but remain somewhat formal and descriptive.
Use British English language and express their story in first-person language.
"""

# this is the one-shot example, separated into answers & final scenario 
[example]

conversation = """
Question: What was happening at the time?
Answer: "we were preparing dinner. Child was helping me."
Question: What did you do or say to use praise with your child and how did your child react?
Answer: "They saw that I needed help clearing up. I said well done and described what they did and why I was grateful."
Question: How did that make you feel?
Answer: "proud that my child has noticed and offered to help."
Question: What would you tell a younger version of yourself who is trying to connect with their child? 
Answer: "It's important to notice the little things."
"""

scenario = """
During a recent evening, we were busy preparing dinner together.\
My child was right there with me, eager to lend a hand. As we were working, they noticed I needed help with clearing up. \
Without hesitation, they stepped in to assist. I took a moment to acknowledge their effort by saying 'well done' and explained what they did and why it meant so much to me. This simple act of recognition made me feel incredibly proud. \
It reminded me of the importance of noticing and appreciating the little things our children do. \
If I could speak to a younger version of myself, I would emphasize how powerful it is to use praise and to always be aware of those small, yet significant, moments.
"""
